const TEAM_COUNTRY_CODE: Record<string, string> = {
  "México": "mx",
  "Sudáfrica": "za",
  "EE.UU.": "us",
  "Paraguay": "py",
  "Catar": "qa",
  "Suiza": "ch",
  "Brasil": "br",
  "Marruecos": "ma",
  "Haití": "ht",
  "Escocia": "gb-sct",
  "Alemania": "de",
  "Curazao": "cw",
  "Países Bajos": "nl",
  "Japón": "jp",
  "Costa de Marfil": "ci",
  "Ecuador": "ec",
  "España": "es",
  "Cabo Verde": "cv",
  "Bélgica": "be",
  "Egipto": "eg",
  "Arabia Saudita": "sa",
  "Uruguay": "uy",
  "Irán": "ir",
  "Nueva Zelanda": "nz",
  "Francia": "fr",
  "Senegal": "sn",
  "Argentina": "ar",
  "Argelia": "dz",
  "Austria": "at",
  "Jordania": "jo",
  "Inglaterra": "gb-eng",
  "Croacia": "hr",
  "Ghana": "gh",
  "Panamá": "pa",
  "Uzbekistán": "uz",
  "Colombia": "co",
  "Canadá": "ca",
  "Corea del Sur": "kr",
  "Australia": "au",
  "República de Corea": "kr",
  "Gales": "gb-wls",
  "Portugal": "pt",
  "Italia": "it",
  "Chile": "cl",
  "Perú": "pe",
  "Camerún": "cm",
  "Nigeria": "ng",
  "Túnez": "tn",
  "Serbia": "rs",
  "Dinamarca": "dk",
  "Suecia": "se",
  "Polonia": "pl",
  "Noruega": "no",
};

const TEAM_GROUP: Record<string, string> = {
  "México": "Grupo A",
  "Sudáfrica": "Grupo A",
  "Corea del Sur": "Grupo A",
  "EE.UU.": "Grupo B",
  "Paraguay": "Grupo B",
  "Australia": "Grupo B",
  "Catar": "Grupo C",
  "Suiza": "Grupo C",
  "Canadá": "Grupo C",
  "Brasil": "Grupo D",
  "Marruecos": "Grupo D",
  "Haití": "Grupo D",
  "Escocia": "Grupo D",
  "Bélgica": "Grupo E",
  "Egipto": "Grupo E",
  "Irán": "Grupo E",
  "Nueva Zelanda": "Grupo E",
  "Alemania": "Grupo F",
  "Curazao": "Grupo F",
  "Austria": "Grupo F",
  "Jordania": "Grupo F",
  "Países Bajos": "Grupo G",
  "Japón": "Grupo G",
  "Costa de Marfil": "Grupo G",
  "Ecuador": "Grupo G",
  "España": "Grupo H",
  "Cabo Verde": "Grupo H",
  "Arabia Saudita": "Grupo H",
  "Uruguay": "Grupo H",
  "Francia": "Grupo I",
  "Senegal": "Grupo I",
  "Argentina": "Grupo I",
  "Argelia": "Grupo I",
  "Inglaterra": "Grupo J",
  "Croacia": "Grupo J",
  "Ghana": "Grupo J",
  "Panamá": "Grupo J",
  "Uzbekistán": "Grupo K",
  "Colombia": "Grupo K",
};

export function getCountryCode(teamName: string): string {
  return TEAM_COUNTRY_CODE[teamName] ?? "";
}

export function getGroupName(homeTeam: string, awayTeam: string): string {
  return TEAM_GROUP[homeTeam] ?? TEAM_GROUP[awayTeam] ?? "Fase de grupos";
}
