import { CalendarEvent } from "@/types/event";
import { TBD } from "@/utils/constants";

const MOCK_EVENTS: CalendarEvent[] = [
  {
    id: "1",
    name: "México vs Sudáfrica",
    groupName: "Grupo A",
    time: "14:00",
    startDate: new Date("2026-06-11T14:00:00"),
    league: "Copa Mundial 2026",
    participants: [
      { id: "1a", name: "México", country: "MX", role: "Home", isSponsored: true, score: 1 },
      { id: "1b", name: "Sudáfrica", country: "ZA", role: "Away", score: 0 },
    ],
    hasStats: true,
    hasBetBuilder: true,
    isEarlyPayout: true,
    hasLiveStream: true,
  },
  {
    id: "2",
    name: `República de Corea vs ${TBD}`,
    groupName: "Grupo A",
    time: "14:00",
    startDate: new Date("2026-06-11T14:00:00"),
    league: "Copa Mundial 2026",
    participants: [
      { id: "2a", name: "República de Corea", country: "KR", role: "Home" },
      { id: "2b", name: TBD, country: "", role: "Away" },
    ],
    hasStats: true,
    hasBetBuilder: true,
    isEarlyPayout: true,
  },
  {
    id: "3",
    name: `Canadá vs ${TBD}`,
    groupName: "Grupo B",
    time: "14:00",
    startDate: new Date("2026-06-12T14:00:00"),
    league: "Copa Mundial 2026",
    participants: [
      { id: "3a", name: "Canadá", country: "CA", role: "Home" },
      { id: "3b", name: TBD, country: "", role: "Away" },
    ],
    hasStats: true,
    hasBetBuilder: true,
    isEarlyPayout: true,
  },
  {
    id: "4",
    name: "Estados Unidos vs Paraguay",
    groupName: "Grupo D",
    time: "20:00",
    startDate: new Date("2026-06-12T20:00:00"),
    league: "Copa Mundial 2026",
    participants: [
      { id: "4a", name: "Estados Unidos", country: "US", role: "Home" },
      { id: "4b", name: "Paraguay", country: "PY", role: "Away" },
    ],
    hasStats: true,
    hasBetBuilder: true,
    isEarlyPayout: true,
  },
  {
    id: "5",
    name: "Catar vs Suiza",
    groupName: "Grupo B",
    time: "14:00",
    startDate: new Date("2026-06-13T14:00:00"),
    league: "Copa Mundial 2026",
    participants: [
      { id: "5a", name: "Catar", country: "QA", role: "Home" },
      { id: "5b", name: "Suiza", country: "CH", role: "Away" },
    ],
    hasStats: true,
    hasBetBuilder: true,
    isEarlyPayout: true,
  },
  {
    id: "6",
    name: "Brasil vs Marruecos",
    groupName: "Grupo C",
    time: "17:00",
    startDate: new Date("2026-06-13T17:00:00"),
    league: "Copa Mundial 2026",
    participants: [
      { id: "6a", name: "Brasil", country: "BR", role: "Home" },
      { id: "6b", name: "Marruecos", country: "MA", role: "Away" },
    ],
    hasStats: true,
    hasBetBuilder: true,
    isEarlyPayout: true,
  },
  {
    id: "8",
    name: `${TBD} vs ${TBD}`,
    groupName: "16vos",
    time: "16:00",
    startDate: new Date("2026-06-13T16:00:00"),
    league: "Copa Mundial 2026",
    participants: [
      { id: "8a", name: TBD, country: "", role: "Home" },
      { id: "8b", name: TBD, country: "", role: "Away" },
    ],
    hasStats: false,
    hasBetBuilder: false,
    isEarlyPayout: false,
  },
  {
    id: "7",
    name: "Haití vs Escocia",
    groupName: "Grupo C",
    time: "20:00",
    startDate: new Date("2026-06-13T20:00:00"),
    league: "Copa Mundial 2026",
    participants: [
      { id: "7a", name: "Haití", country: "HT", role: "Home" },
      { id: "7b", name: "Escocia", country: "GB-SCT", role: "Away" },
    ],
    hasStats: true,
    hasBetBuilder: true,
    isEarlyPayout: true,
  },
];

export default MOCK_EVENTS;
